### ISSUE TITLE
请问还有什么已知的坑吗？

### ISSUE THREAD

**Issue by hehex9** [yoaicom/react-native-social-kit#1]
RT
看到 zt-share 分支的功能已经很齐了，想在生产环境使用，请问还有已知的问题需要注意吗？

**Comment by ldn0x7dc** [comment]
@pcxiong 
目前还在开发中，目测一周内可以发布。
发布前接口可能会有不少改动，请再等几天吧。

**Comment by hehex9** [comment]
![n s nlvjo0 x w ifxowc](https://cloud.githubusercontent.com/assets/9209882/17956586/a66d9f00-6abd-11e6-9ea6-9b7cc49a60eb.gif)

多谢。
